%Requirements: topologies generated with BRITE simulator
%This code associates at each square meter in a 10 km x 10 km area an
%attachment point, following topologies generated by the BRITE simulator 
N=input('Number of nodes:'); % Enter the number of nodes per topology
num_topo=input('Number of topologies:'); % Enter the number of topologies generated

voro_bind=ones(10000,10000); %Instantiate the Voronoi map for a 10 km x 10 km area

for h=1:num_topo
    [c1, c2, c3] = textread(sprintf('output-%d/outsim-%d',N, h), '%u %u %u'); % Load the topology generated by BRITE
    
    NodeID=c1(1:N,1)+1;
    coor_X=c2(1:N,1)+1;
    coor_Y=c3(1:N,1)+1;
    coor_mat=[NodeID coor_X coor_Y]; %Instantiate the matrix of coordinates
    
    LinkID=c1(N+1:3*N-3,1);
    NodeID_1=c2(N+1:3*N-3,1)+1;
    NodeID_2=c3(N+1:3*N-3,1)+1;
    link_mat=[LinkID NodeID_1 NodeID_2];%Instantiate the matrix of links
    sprintf('%d/%d',h,num_topo) %Progress indicator
    TR=delaunayTriangulation([coor_X coor_Y]); %Generate the delaunay triangulation
    for j=1:10000
        for i=1:10000
            voro_bind(i,j)=nearestNeighbor(TR,[i j]); %Associate each square meter at the nearest attachment point
        end
    end
    save(sprintf('map/voronoi_mapping-%d-%d.mat',N,h),'voro_bind')
end
